// schema start for exec plugin

export const exec = [
  {
    title: "max_threads",
    type: "text",
    required: false,
    withQuotes: false,
  },
  {
    title: "min_output_tasks",
    type: "text",
    required: false,
    withQuotes: false,
  },
  {
    title: "preview_sample_buffer_bytes",
    type: "text",
    required: false,
    defaultValue: "32768",
    withQuotes: false,
  },
];

// schema end for exec plugin

// schema start for in & out plugin

export const mysqlSchema = {
  common: [
    {
      title: "driver_path",
      type: "text",
      required: true,
      withQuotes: false,
    },
    {
      title: "host",
      type: "text",
      required: true,
      withQuotes: false,
    },
    {
      title: "port",
      type: "text",
      defaultValue: "3306",
      required: true,
      withQuotes: false,
    },
    {
      title: "user",
      type: "text",
      required: true,
      withQuotes: false,
    },
    {
      title: "password",
      type: "text",
      defaultValue: "",
      required: true,
      withQuotes: false,
    },
    {
      title: "ssl",
      type: "radio",
      defaultValue: "false",
      options: ["true", "false"],
      required: false,
      withQuotes: false,
    },
    {
      title: "database",
      type: "text",
      required: true,
      withQuotes: false,
    },
    {
      title: "options",
      type: "multiple_key_value",
      required: false,
      options: [
        {
          title: "key",
          type: "text",
          required: true,
          withQuotes: false,
        },
        {
          title: "value",
          type: "text",
          required: true,
          withQuotes: true,
        }
      ]
    },
    {
      title: "column_options",
      type: "multiple_key_objects",
      required: false,
      options: [
        {
          title: "value_type",
          type: "text",
          required: false,
          withQuotes: false,
        },
        {
          title: "type",
          type: "text",
          required: false,
          withQuotes: true,
        },
        {
          title: "timestamp_format",
          type: "text",
          required: false,
          withQuotes: true,
        },
        {
          title: "timezone",
          type: "text",
          required: false,
          withQuotes: true,
        },
      ],
    },
    {
      title: "default_timezone",
      type: "text",
      defaultValue: "UTC",
      required: false,
      withQuotes: false,
    },
  ],

  input: [
    {
      title: "query",
      type: "textarea",
      required: true,
      withQuotes: false,
      hiddenWhen: "table",
    },
    {
      title: "use_raw_query_with_incremental",
      type: "radio",
      defaultValue: "false",
      options: ["true", "false"],
      required: true,
      withQuotes: false,
      showWhen: "query",
    },
    {
      title: "table",
      type: "text",
      required: false,
      withQuotes: false,
      hiddenWhen: "query",
    },
    {
      title: "select",
      type: "text",
      required: false,
      withQuotes: false,
      showWhen: "table",
    },
    {
      title: "where",
      type: "text",
      required: false,
      withQuotes: false,
      showWhen: "table",
    },
    {
      title: "order_by",
      type: "text",
      required: false,
      withQuotes: false,
      showWhen: "table",
    },
    {
      title: "fetch_rows",
      type: "text",
      defaultValue: "10000",
      required: false,
      withQuotes: false,
    },
    {
      title: "connect_timeout",
      type: "text",
      defaultValue: "300",
      required: false,
      withQuotes: false,
    },
    {
      title: "socket_timeout",
      type: "text",
      defaultValue: "1800",
      required: false,
      withQuotes: false,
    },
    {
      title: "incremental",
      type: "radio",
      defaultValue: "false",
      options: ["true", "false"],
      required: false,
      withQuotes: false,
    },
    {
      title: "incremental_columns",
      type: "array_of_strings",
      required: false,
      withQuotes: false,
    },
    {
      title: "last_record",
      type: "array_of_strings",
      required: false,
      withQuotes: false,
    },
    {
      title: "use_legacy_datetime_code",
      type: "radio",
      defaultValue: "false",
      options: ["true", "false"],
      required: false,
      withQuotes: false,
    },
    {
      title: "default_column_options",
      type: "multiple_key_objects",
      required: false,
      options: [
        {
          title: "value_type",
          type: "text",
          required: false,
          withQuotes: false,
        },
        {
          title: "type",
          type: "text",
          required: false,
          withQuotes: true,
        },
        {
          title: "timestamp_format",
          type: "text",
          required: false,
          withQuotes: true,
        },
        {
          title: "timezone",
          type: "text",
          required: false,
          withQuotes: true,
        },
      ],
    },
    {
      title: "before_setup",
      type: "text",
      required: false,
      withQuotes: false,
    },
    {
      title: "before_select",
      type: "text",
      required: false,
      withQuotes: false,
    },
    {
      title: "after_select",
      type: "text",
      required: false,
      withQuotes: false,
    },
  ],
  output: [
    {
      title: "temp_database",
      type: "text",
      required: false,
      withQuotes: false,
    },
    {
      title: "table",
      type: "text",
      required: true,
      withQuotes: false,
    },
    {
      title: "create_table_constraint",
      type: "text",
      required: false,
      withQuotes: false,
    },
    {
      title: "create_table_option",
      type: "text",
      required: false,
      withQuotes: false,
    },
    {
      title: "transaction_isolation",
      type: "text",
      required: false,
      withQuotes: false,
    },
    {
      title: "retry_limit",
      type: "text",
      defaultValue: "12",
      required: false,
      withQuotes: false,
    },
    {
      title: "retry_wait",
      type: "text",
      defaultValue: "1000",
      required: false,
      withQuotes: false,
    },
    {
      title: "max_retry_wait",
      type: "text",
      defaultValue: "1800000",
      required: false,
      withQuotes: false,
    },
    {
      title: "mode",
      type: "text",
      required: true,
      withQuotes: true,
    },
    {
      title: "merge_rule",
      type: "text",
      required: false,
      withQuotes: false,
    },
    {
      title: "batch_size",
      type: "text",
      defaultValue: "16777216",
      required: false,
      withQuotes: false,
    },
    {
      title: "before_load",
      type: "text",
      required: false,
      withQuotes: false,
    },
    {
      title: "after_load",
      type: "text",
      required: false,
      withQuotes: false,
    },
  ],
};

export const jdbcSchema = {
  common: [
    {
      title: "driver_path",
      type: "text",
      required: true,
      withQuotes: false,
    },
    {
      title: "driver_class",
      type: "text",
      required: true,
      withQuotes: false,
    },
    {
      title: "url",
      type: "text",
      required: true,
      withQuotes: false,
    },
    {
      title: "user",
      type: "text",
      required: false,
      withQuotes: false,
    },
    {
      title: "password",
      type: "text",
      required: false,
      withQuotes: false,
    },
    {
      title: "schema",
      type: "text",
      required: false,
      withQuotes: false,
    },
    // {
    //   title: "options",
    //   type: "array_of_objects",
    //   required: false,
    //   options: [{}],
    // },
    {
      title: "default_timezone",
      type: "text",
      defaultValue: "UTC",
      required: false,
      withQuotes: false,
    },
    {
      title: "column_options",
      type: "multiple_key_objects",
      required: false,
      options: [
        {
          title: "value_type",
          type: "text",
          required: false,
          withQuotes: false,
        },
        {
          title: "type",
          type: "text",
          required: false,
          withQuotes: true,
        },
        {
          title: "timestamp_format",
          type: "text",
          required: false,
          withQuotes: true,
        },
        {
          title: "timezone",
          type: "text",
          required: false,
          withQuotes: true,
        },
      ],
    },
  ],
  input: [
    {
      title: "fetch_rows",
      type: "text",
      defaultValue: "10000",
      required: false,
      withQuotes: false,
    },
    {
      title: "connect_timeout",
      type: "text",
      required: false,
      withQuotes: false,
    },
    {
      title: "socket_timeout",
      type: "text",
      defaultValue: "10000",
      required: false,
      withQuotes: false,
    },
    {
      title: "query",
      type: "textarea",
      required: true,
      withQuotes: false,
      hiddenWhen: "table",
    },
    {
      title: "use_raw_query_with_incremental",
      type: "radio",
      defaultValue: "false",
      options: ["true", "false"],
      required: true,
      withQuotes: false,
      showWhen: "query",
    },
    {
      title: "table",
      type: "text",
      required: false,
      withQuotes: false,
      hiddenWhen: "query",
    },
    {
      title: "select",
      type: "text",
      required: false,
      withQuotes: false,
      showWhen: "table",
    },
    {
      title: "where",
      type: "text",
      required: false,
      withQuotes: false,
      showWhen: "table",
    },
    {
      title: "order_by",
      type: "text",
      required: false,
      withQuotes: false,
      showWhen: "table",
    },
    {
      title: "default_column_options",
      type: "multiple_key_objects",
      required: false,
      options: [
        {
          title: "value_type",
          type: "text",
          required: false,
          withQuotes: false,
        },
        {
          title: "type",
          type: "text",
          required: false,
          withQuotes: true,
        },
        {
          title: "timestamp_format",
          type: "text",
          required: false,
          withQuotes: true,
        },
        {
          title: "timezone",
          type: "text",
          required: false,
          withQuotes: true,
        },
      ],
    },
    {
      title: "before_setup",
      type: "text",
      required: false,
      withQuotes: false,
    },
    {
      title: "before_select",
      type: "text",
      required: false,
      withQuotes: false,
    },
    {
      title: "after_select",
      type: "text",
      required: false,
      withQuotes: false,
    },
  ],
  output: [
    {
      title: "table",
      type: "text",
      required: true,
      withQuotes: false,
    },
    {
      title: "create_table_constraint",
      type: "text",
      required: false,
      withQuotes: false,
    },
    {
      title: "create_table_option",
      type: "text",
      required: false,
      withQuotes: false,
    },
    {
      title: "transaction_isolation",
      type: "text",
      required: false,
      withQuotes: false,
    },
    {
      title: "retry_limit",
      type: "text",
      defaultValue: "12",
      required: false,
      withQuotes: false,
    },
    {
      title: "retry_wait",
      type: "text",
      defaultValue: "1000",
      required: false,
      withQuotes: false,
    },
    {
      title: "max_retry_wait",
      type: "text",
      defaultValue: "1800000",
      required: false,
      withQuotes: false,
    },
    {
      title: "mode",
      type: "text",
      required: true,
      withQuotes: true,
    },
    {
      title: "batch_size",
      type: "text",
      defaultValue: "16777216",
      required: false,
      withQuotes: false,
    },
    {
      title: "max_table_name_length",
      type: "text",
      defaultValue: "256",
      required: false,
      withQuotes: false,
    },
    {
      title: "before_load",
      type: "text",
      required: false,
      withQuotes: false,
    },
    {
      title: "after_load",
      type: "text",
      required: false,
      withQuotes: false,
    },
  ],
};

export const postgresSchema = {
  common: [
    {
      title: "driver_path",
      type: "text",
      required: false,
      withQuotes: false,
    },
    {
      title: "host",
      type: "text",
      required: true,
      withQuotes: false,
    },
    {
      title: "port",
      type: "text",
      defaultValue: "3306",
      required: true,
      withQuotes: false,
    },
    {
      title: "user",
      type: "text",
      required: true,
      withQuotes: false,
    },
    {
      title: "password",
      type: "text",
      defaultValue: "",
      required: true,
      withQuotes: false,
    },
    {
      title: "database",
      type: "text",
      required: true,
      withQuotes: false,
    },
    {
      title: "schema",
      type: "text",
      required: false,
      withQuotes: false,
    },
    // {
    //   title: "options",
    //   type: "array_of_objects",
    //   required: false,
    //   options: [{}],
    // },
    {
      title: "ssl",
      type: "radio",
      defaultValue: "false",
      options: ["true", "false"],
      required: false,
      withQuotes: false,
    },
    {
      title: "column_options",
      type: "multiple_key_objects",
      required: false,
      options: [
        {
          title: "value_type",
          type: "text",
          required: false,
          withQuotes: false,
        },
        {
          title: "type",
          type: "text",
          required: false,
          withQuotes: true,
        },
        {
          title: "timestamp_format",
          type: "text",
          required: false,
          withQuotes: true,
        },
        {
          title: "timezone",
          type: "text",
          required: false,
          withQuotes: true,
        },
      ],
    },
    {
      title: "default_timezone",
      type: "text",
      defaultValue: "UTC",
      required: false,
      withQuotes: false,
    },
  ],

  input: [
    {
      title: "query",
      type: "textarea",
      required: true,
      withQuotes: false,
      hiddenWhen: "table",
    },
    {
      title: "use_raw_query_with_incremental",
      type: "radio",
      defaultValue: "false",
      options: ["true", "false"],
      required: true,
      withQuotes: false,
      showWhen: "query",
    },
    {
      title: "table",
      type: "text",
      required: false,
      withQuotes: false,
      hiddenWhen: "query",
    },
    {
      title: "select",
      type: "text",
      required: false,
      withQuotes: false,
      showWhen: "table",
    },
    {
      title: "where",
      type: "text",
      required: false,
      withQuotes: false,
      showWhen: "table",
    },
    {
      title: "order_by",
      type: "text",
      required: false,
      withQuotes: false,
      showWhen: "table",
    },
    {
      title: "fetch_rows",
      type: "text",
      defaultValue: "10000",
      required: false,
      withQuotes: false,
    },
    {
      title: "connect_timeout",
      type: "text",
      defaultValue: "300",
      required: false,
      withQuotes: false,
    },
    {
      title: "socket_timeout",
      type: "text",
      defaultValue: "1800",
      required: false,
      withQuotes: false,
    },
    {
      title: "statement_timeout_millis",
      type: "text",
      required: false,
      withQuotes: false,
    },
    {
      title: "application_name",
      type: "text",
      defaultValue: "embulk-input-postgresql",
      required: false,
      withQuotes: false,
    },
    {
      title: "incremental",
      type: "radio",
      defaultValue: "false",
      options: ["true", "false"],
      required: false,
      withQuotes: false,
    },
    {
      title: "incremental_columns",
      type: "array_of_strings",
      required: false,
      withQuotes: false,
    },
    {
      title: "last_record",
      type: "array_of_strings",
      required: false,
      withQuotes: false,
    },
    {
      title: "default_column_options",
      type: "multiple_key_objects",
      required: false,
      options: [
        {
          title: "value_type",
          type: "text",
          required: false,
          withQuotes: false,
        },
        {
          title: "type",
          type: "text",
          required: false,
          withQuotes: true,
        },
        {
          title: "timestamp_format",
          type: "text",
          required: false,
          withQuotes: true,
        },
        {
          title: "timezone",
          type: "text",
          required: false,
          withQuotes: true,
        },
      ],
    },
    {
      title: "before_setup",
      type: "text",
      required: false,
      withQuotes: false,
    },
    {
      title: "before_select",
      type: "text",
      required: false,
      withQuotes: false,
    },
    {
      title: "after_select",
      type: "text",
      required: false,
      withQuotes: false,
    },
  ],
  output: [
    {
      title: "temp_schema",
      type: "text",
      required: false,
      withQuotes: false,
    },
    {
      title: "table",
      type: "text",
      required: true,
      withQuotes: false,
    },
    {
      title: "create_table_constraint",
      type: "text",
      required: false,
      withQuotes: false,
    },
    {
      title: "create_table_option",
      type: "text",
      required: false,
      withQuotes: false,
    },
    {
      title: "transaction_isolation",
      type: "text",
      required: false,
      withQuotes: false,
    },
    {
      title: "retry_limit",
      type: "text",
      defaultValue: "12",
      required: false,
      withQuotes: false,
    },
    {
      title: "retry_wait",
      type: "text",
      defaultValue: "1000",
      required: false,
      withQuotes: false,
    },
    {
      title: "max_retry_wait",
      type: "text",
      defaultValue: "1800000",
      required: false,
      withQuotes: false,
    },
    {
      title: "mode",
      type: "text",
      required: true,
      withQuotes: true,
    },
    {
      title: "merge_keys",
      type: "text",
      required: false,
      withQuotes: false,
    },
    {
      title: "merge_rule",
      type: "text",
      required: false,
      withQuotes: false,
    },
    {
      title: "batch_size",
      type: "text",
      defaultValue: "16777216",
      required: false,
      withQuotes: false,
    },
    {
      title: "role_name",
      type: "text",
      required: false,
      withQuotes: false,
    },
    {
      title: "before_load",
      type: "text",
      required: false,
      withQuotes: false,
    },
    {
      title: "after_load",
      type: "text",
      required: false,
      withQuotes: false,
    },
  ],
};

export const csvSchema = {
  common: [
    {
      title: "path_prefix",
      type: "text",
      required: true,
      withQuotes: false,
    },
  ],
  input: [
    {
      title: "decoders",
      type: "array_of_objects",
      required: false,
      options: [
        {
          title: "type",
          type: "text",
          required: true,
          withQuotes: false,
        },
      ],
    },
    {
      title: "parser",
      type: "nested",
      required: true,
      options: [
        {
          title: "charset",
          type: "text",
          required: false,
          defaultValue: "UTF-8",
          withQuotes: false,
        },
        {
          title: "newline",
          type: "text",
          required: true,
          defaultValue: "CRLF",
          withQuotes: false,
        },
        {
          title: "type",
          type: "text",
          required: true,
          defaultValue: "csv",
          withQuotes: false,
        },
        {
          title: "delimiter",
          type: "text",
          required: true,
          defaultValue: ",",
          withQuotes: true,
        },
        {
          title: "quote",
          type: "text",
          required: true,
          defaultValue: '"',
          withQuotes: true,
        },
        {
          title: "escape",
          type: "text",
          required: true,
          defaultValue: "\\",
          withQuotes: true,
        },
        {
          title: "null_string",
          type: "text",
          required: true,
          defaultValue: "NULL",
          withQuotes: true,
        },
        {
          title: "skip_header_lines",
          type: "text",
          required: true,
          defaultValue: "0",
          withQuotes: false,
        },
        {
          title: "trim_if_not_quoted",
          type: "radio",
          required: false,
          defaultValue: "false",
          options: ["true", "false"],
          withQuotes: false,
        },
        {
          title: "quotes_in_quoted_fields",
          type: "text",
          required: false,
          defaultValue: "ACCEPT_ONLY_RFC4180_ESCAPED",
          withQuotes: false,
        },
        {
          title: "comment_line_marker",
          type: "text",
          required: false,
          defaultValue: "NULL",
          withQuotes: false,
        },
        {
          title: "allow_optional_columns",
          type: "radio",
          required: false,
          defaultValue: "false",
          options: ["true", "false"],
          withQuotes: false,
        },
        {
          title: "allow_extra_columns",
          type: "radio",
          required: false,
          defaultValue: "false",
          options: ["true", "false"],
          withQuotes: false,
        },
        {
          title: "max_quoted_size_limit",
          type: "text",
          required: false,
          defaultValue: "131072",
          withQuotes: false,
        },
        {
          title: "stop_on_invalid_record",
          type: "radio",
          required: false,
          defaultValue: "false",
          options: ["true", "false"],
          withQuotes: false,
        },
        {
          title: "default_timezone",
          type: "text",
          required: false,
          defaultValue: "UTC",
          withQuotes: false,
        },
        {
          title: "line_delimiter_recognized",
          type: "text",
          required: false,
          withQuotes: false,
        },
        {
          title: "columns",
          type: "array_of_objects",
          required: true,
          options: [
            {
              title: "name",
              type: "text",
              required: false,
              withQuotes: false,
            },
            {
              title: "type",
              type: "text",
              required: false,
              withQuotes: false,
            },
            {
              title: "format",
              type: "text",
              required: false,
              withQuotes: false,
            },
            {
              title: "date",
              type: "text",
              required: false,
              withQuotes: false,
            },
          ],
        },
      ],
    },
    {
      title: "last_path",
      type: "text",
      required: false,
      withQuotes: false,
    },
    {
      title: "follow_symlinks",
      type: "radio",
      required: false,
      defaultValue: "false",
      options: ["true", "false"],
      withQuotes: false,
    },
  ],
  output: [
    {
      title: "sequence_format",
      type: "text",
      defaultValue: "%03d.%02d.",
      required: false,
      withQuotes: false,
    },
    {
      title: "file_ext",
      type: "text",
      required: true,
      withQuotes: false,
    },
    {
      title: "formatter",
      type: "nested",
      required: true,
      options: [
        {
          title: "type",
          type: "text",
          required: true,
          defaultValue: "csv",
          withQuotes: false,
        },
        {
          title: "delimiter",
          type: "text",
          required: true,
          defaultValue: ",",
          withQuotes: false,
        },
        {
          title: "newline",
          type: "text",
          required: true,
          defaultValue: "CRLF",
          withQuotes: false,
        },
        {
          title: "newline_in_field",
          type: "text",
          required: true,
          defaultValue: "LF",
          withQuotes: false,
        },
        {
          title: "charset",
          type: "text",
          required: true,
          defaultValue: "UTF-8",
          withQuotes: false,
        },
        {
          title: "quote_policy",
          type: "text",
          required: true,
          defaultValue: "MINIMAL",
          withQuotes: false,
        },
        {
          title: "quote",
          type: "text",
          required: true,
          defaultValue: '"',
          withQuotes: false,
        },
        {
          title: "escape",
          type: "text",
          required: true,
          withQuotes: false,
        },
        {
          title: "null_string",
          type: "text",
          required: true,
          withQuotes: false,
        },
        {
          title: "default_timezone",
          type: "text",
          required: true,
          defaultValue: "UTC",
          withQuotes: false,
        },
        {
          title: "header_line",
          type: "radio",
          required: false,
          defaultValue: "true",
          options: ["true", "false"],
          withQuotes: false,
        },
        {
          title: "column_options",
          type: "array_of_objects",
          required: false,
          options: [
            {
              title: "timezone",
              type: "text",
              required: false,
              withQuotes: false,
            },
            {
              title: "format",
              type: "text",
              required: true,
              defaultValue: "%Y-%m-%d %H:%M:%S.%6N %z",
              withQuotes: false,
            },
          ],
        },
      ],
    },
    {
      title: "encoders",
      type: "array_of_objects",
      required: false,
      options: [
        {
          title: "type",
          type: "text",
          required: true,
          withQuotes: false,
        },
        {
          title: "level",
          type: "text",
          required: false,
          withQuotes: false,
        },
      ],
    },
  ],
};

export const msSqlSchema = {
  common: [
    {
      title: "driver_path",
      type: "text",
      required: false,
      withQuotes: false,
    },
    {
      title: "driver_type",
      type: "text",
      required: true,
      withQuotes: false,
    },
    {
      title: "host",
      type: "text",
      required: true,
      withQuotes: false,
    },
    {
      title: "port",
      type: "text",
      defaultValue: "1433",
      required: true,
      withQuotes: false,
    },
    {
      title: "integratedSecutiry",
      type: "radio",
      defaultValue: "false",
      options: ["true", "false"],
      required: false,
      withQuotes: false,
    },
    {
      title: "user",
      type: "text",
      required: true,
      withQuotes: false,
    },
    {
      title: "password",
      type: "text",
      defaultValue: "",
      required: true,
      withQuotes: false,
    },
    {
      title: "instance",
      type: "text",
      required: false,
      withQuotes: false,
    },
    {
      title: "database",
      type: "text",
      required: true,
      withQuotes: false,
    },
    {
      title: "schema",
      type: "text",
      required: false,
      withQuotes: false,
    },
    {
      title: "url",
      type: "text",
      required: false,
      withQuotes: false,
    },
    // {
    //   title: "options",
    //   type: "multi",
    //   required: false,
    //   options: [{}],
    // },
    {
      title: "column_options",
      type: "multiple_key_objects",
      required: false,
      options: [
        {
          title: "value_type",
          type: "text",
          required: false,
          withQuotes: false,
        },
        {
          title: "type",
          type: "text",
          required: false,
          withQuotes: true,
        },
        {
          title: "timestamp_format",
          type: "text",
          required: false,
          withQuotes: true,
        },
        {
          title: "timezone",
          type: "text",
          required: false,
          withQuotes: true,
        },
      ],
    },
    {
      title: "default_timezone",
      type: "text",
      defaultValue: "UTC",
      required: false,
      withQuotes: false,
    },
    {
      title: "connect_timeout",
      type: "text",
      defaultValue: "300",
      required: false,
      withQuotes: false,
    },
    {
      title: "socket_timeout",
      type: "text",
      defaultValue: "1800",
      required: false,
      withQuotes: false,
    },
  ],

  input: [
    {
      title: "query",
      type: "textarea",
      required: true,
      withQuotes: false,
      hiddenWhen: "table",
    },
    {
      title: "use_raw_query_with_incremental",
      type: "radio",
      defaultValue: "false",
      options: ["true", "false"],
      required: true,
      withQuotes: false,
      showWhen: "query",
    },
    {
      title: "table",
      type: "text",
      required: false,
      withQuotes: false,
      hiddenWhen: "query",
    },
    {
      title: "transaction_isolation_level",
      type: "text",
      required: false,
      withQuotes: false,
      showWhen: "table",
    },
    {
      title: "select",
      type: "text",
      required: false,
      withQuotes: false,
      showWhen: "table",
    },
    {
      title: "where",
      type: "text",
      required: false,
      withQuotes: false,
      showWhen: "table",
    },
    {
      title: "order_by",
      type: "text",
      required: false,
      withQuotes: false,
      showWhen: "table",
    },
    {
      title: "fetch_rows",
      type: "text",
      defaultValue: "10000",
      required: false,
      withQuotes: false,
    },
    {
      title: "application_name",
      type: "text",
      defaultValue: "embulk-input-sqlserver",
      required: false,
      withQuotes: false,
    },
    {
      title: "incremental",
      type: "radio",
      defaultValue: "false",
      options: ["true", "false"],
      required: false,
      withQuotes: false,
    },
    {
      title: "incremental_columns",
      type: "array_of_strings",
      required: false,
      withQuotes: false,
    },
     {
      title: "last_record",
      type: "array_of_strings",
      required: false,
      withQuotes: false,
    },
    {
      title: "default_column_options",
      type: "multiple_key_objects",
      required: false,
      options: [
        {
          title: "value_type",
          type: "text",
          required: false,
          withQuotes: false,
        },
        {
          title: "type",
          type: "text",
          required: false,
          withQuotes: true,
        },
        {
          title: "timestamp_format",
          type: "text",
          required: false,
          withQuotes: true,
        },
        {
          title: "timezone",
          type: "text",
          required: false,
          withQuotes: true,
        },
      ],
    },
    {
      title: "before_setup",
      type: "text",
      required: false,
      withQuotes: false,
    },
    {
      title: "before_select",
      type: "text",
      required: false,
      withQuotes: false,
    },
    {
      title: "after_select",
      type: "text",
      requirschemaed: false,
      withQuotes: false,
    },
  ],
  output: [
    {
      title: "temp_schema",
      type: "text",
      required: false,
      withQuotes: false,
    },
    {
      title: "table",
      type: "text",
      required: true,
      withQuotes: false,
    },
    {
      title: "create_table_constraint",
      type: "text",
      required: false,
      withQuotes: false,
    },
    {
      title: "create_table_option",
      type: "text",
      required: false,
      withQuotes: false,
    },
    {
      title: "transaction_isolation",
      type: "text",
      required: false,
      withQuotes: false,
    },
    {
      title: "retry_limit",
      type: "text",
      defaultValue: "12",
      required: false,
      withQuotes: false,
    },
    {
      title: "retry_wait",
      type: "text",
      defaultValue: "1000",
      required: false,
      withQuotes: false,
    },
    {
      title: "max_retry_wait",
      type: "text",
      defaultValue: "1800000",
      required: false,
      withQuotes: false,
    },
    {
      title: "mode",
      type: "text",
      required: true,
      withQuotes: true,
    },
    {
      title: "merge_keys",
      type: "array_of_strings",
      required: false,
      withQuotes: false,
    },
    {
      title: "merge_rule",
      type: "array_of_strings",
      required: false,
      withQuotes: false,
    },
    {
      title: "insert_method",
      type: "text",
      required: false,
      withQuotes: false,
    },
    {
      title: "native_driver",
      type: "text",
      defaultValue: "{SQL Server Native Client 11.0}",
      required: false,
      withQuotes: false,
    },
    {
      title: "database_encoding",
      type: "text",
      defaultValue: "MS932",
      required: false,
      withQuotes: false,
    },
    {
      title: "batch_size",
      type: "text",
      defaultValue: "16777216",
      required: false,
      withQuotes: false,
    },
    {
      title: "before_load",
      type: "text",
      required: false,
      withQuotes: false,
    },
    {
      title: "after_load",
      type: "text",
      required: false,
      withQuotes: false,
    },
  ],
};

export const sendEmailSchema = {
  common: [],
  input: [],
  output: [
    {
      title: "to",
      type: "text",
      required: true,
      withQuotes: false,
    },
    {
      title: "from",
      type: "text",
      required: true,
      withQuotes: false,
    },
    {
      title: "port",
      type: "text",
      required: true,
      withQuotes: false,
    },
    {
      title: "host",
      type: "text",
      required: true,
      withQuotes: false,
    },
    {
      title: "row",
      type: "text",
      required: true,
      withQuotes: false,
    },
  ],
};

// schema end for in & out plugin

// schema start for filters plugin

export const filters = [
  {
    title: "columns",
    type: "nested_without_title",
    required: false,
    options: [
      {
        title: "type",
        type: "text",
        defaultValue: "column",
        readOnly: true,
        required: true,
        withQuotes: false,
      },
      {
        title: "columns",
        type: "array_of_objects",
        required: true,
        options: [
          {
            title: "name",
            type: "text",
            required: true,
            withQuotes: false,
          },
          {
            title: "src",
            type: "text",
            required: false,
            withQuotes: false,
          },
          {
            title: "default",
            type: "text",
            required: false,
            withQuotes: false,
          },
          {
            title: "type",
            type: "text",
            required: false,
            withQuotes: false,
          },
          {
            title: "format",
            type: "text",
            required: false,
            withQuotes: false,
          },
          {
            title: "timezone",
            type: "text",
            required: false,
            withQuotes: false,
          },
        ],
      },
    ],
  },
  {
    title: "add_columns",
    type: "nested_without_title",
    required: false,
    options: [
      {
        title: "type",
        type: "text",
        defaultValue: "column",
        readOnly: true,
        required: true,
        withQuotes: false,
      },
      {
        title: "add_columns",
        type: "array_of_objects",
        required: false,
        options: [
          {
            title: "name",
            type: "text",
            required: true,
            withQuotes: false,
          },
          {
            title: "src",
            type: "text",
            required: false,
            withQuotes: false,
          },
          {
            title: "default",
            type: "text",
            required: false,
            withQuotes: false,
          },
          {
            title: "type",
            type: "text",
            required: false,
            withQuotes: false,
          },

          {
            title: "format",
            type: "text",
            required: false,
            withQuotes: false,
          },
          {
            title: "timezone",
            type: "text",
            required: false,
            withQuotes: false,
          },
        ],
      },
    ],
  },
  {
    title: "add_time",
    type: "nested_without_title",
    required: false,
    options: [
      {
        title: "type",
        type: "text",
        defaultValue: "add_time",
        readOnly: true,
        required: true,
        withQuotes: false,
      },
      {
        title: "to_column",
        type: "nested",
        required: false,
        options: [
          {
            title: "name",
            type: "text",
            required: true,
            withQuotes: false,
          },
          {
            title: "type",
            type: "text",
            required: true,
            withQuotes: false,
          },
          {
            title: "unix_timestamp_unit",
            type: "text",
            required: false,
            withQuotes: false,
          },
        ],
      },
      {
        title: "from_value",
        type: "nested",
        required: false,
        options: [
          {
            title: "mode",
            type: "text",
            required: true,
            withQuotes: false,
          },
          {
            title: "timestamp_format",
            type: "text",
            required: true,
            withQuotes: false,
          },
          {
            title: "unix_timestamp_unit",
            type: "text",
            required: false,
            withQuotes: false,
          },
          {
            title: "value",
            type: "text",
            required: false,
            withQuotes: false,
          },
          {
            title: "value",
            type: "text",
            required: false,
            withQuotes: false,
          },
          {
            title: "from",
            type: "text",
            required: false,
            withQuotes: false,
          },
          {
            title: "to",
            type: "text",
            required: false,
            withQuotes: false,
          },
        ],
      },
      {
        title: "from_column",
        type: "nested",
        required: false,
        options: [
          {
            title: "name",
            type: "text",
            required: true,
            withQuotes: false,
          },
          {
            title: "unix_timestamp_unit",
            type: "text",
            required: true,
            withQuotes: false,
          },
          {
            title: "timestamp_format",
            type: "text",
            required: true,
            withQuotes: false,
          },
        ],
      },
    ],
  },
  {
    title: "to_json",
    type: "nested_without_title",
    defaultValue: "false",
    required: false,
    options: [
      {
        title: "type",
        type: "text",
        defaultValue: "to_json",
        readOnly: true,
        required: true,
        withQuotes: false,
      },
      {
        title: "column",
        type: "nested",
        required: false,
        options: [
          {
            title: "name",
            type: "text",
            required: true,
            withQuotes: false,
          },
          {
            title: "type",
            type: "text",
            required: true,
            withQuotes: false,
          },
        ],
      },
      {
        title: "skip_if_null",
        type: "array_of_strings",
        required: false,
        withQuotes: false,
      },
      {
        title: "default_timezone",
        type: "text",
        defaultValue: "%Y-%m-%d %H:%M:%S.%N %z",
        required: false,
        withQuotes: false,
      },
    ],
  },
  {
    title: "remove_columns",
    type: "nested_without_title",
    required: false,
    withQuotes: false,
    options: [
      {
        title: "type",
        type: "text",
        defaultValue: "remove_columns",
        readOnly: true,
        required: true,
        withQuotes: false,
      },
      {
        title: "remove",
        type: "array_of_strings",
        required: false,
        withQuotes: false,
      },
      {
        title: "keep",
        type: "array_of_strings",
        required: false,
        withQuotes: false,
      },
      {
        title: "accept_unmatched_columns",
        type: "radio",
        defaultValue: "false",
        required: false,
        withQuotes: false,
        options: ["true", "false"],
      },
    ],
  },
  {
    title: "rename",
    type: "nested_without_title",
    required: false,
    options: [
      {
        title: "type",
        type: "text",
        defaultValue: "rename",
        readOnly: true,
        required: true,
        withQuotes: false,
      },
      {
        title: "rules",
        type: "nested",
        required: false,
        options: [
          {
            title: "character_types",
            type: "nested_without_title",
            required: false,
            options: [
              {
                title: "rule",
                type: "text",
                defaultValue: "character_types",
                readOnly: true,
                required: true,
                withQuotes: false,
              },
              {
                title: "pass_characteres",
                type: "text",
                defaultValue: "",
                required: false,
                withQuotes: true,
              },
              {
                title: "pass_types",
                type: "array_of_strings",
                required: false,
                withQuotes: false,
              },
              {
                title: "replace",
                type: "text",
                defaultValue: "_",
                required: false,
                withQuotes: true,
              },
            ],
          },
          {
            title: "first_character_types",
            type: "nested_without_title",
            required: false,
            options: [
              {
                title: "rule",
                type: "text",
                defaultValue: "first_character_types",
                readOnly: true,
                required: true,
                withQuotes: false,
              },
              {
                title: "pass_characteres",
                type: "text",
                defaultValue: "",
                required: false,
                withQuotes: true,
              },
              {
                title: "pass_types",
                type: "array_of_strings",
                required: false,
                withQuotes: false,
              },
              {
                title: "prefix",
                type: "text",
                defaultValue: "_",
                required: false,
                withQuotes: true,
                hiddenWhen: "replace",
              },
              {
                title: "replace",
                type: "text",
                defaultValue: "_",
                required: false,
                withQuotes: true,
                hiddenWhen: "prefix",
              },
            ],
          },
          {
            title: "lower_to_upper",
            type: "nested_without_title",
            required: false,
            options: [
              {
                title: "rule",
                type: "text",
                defaultValue: "lower_to_upper",
                readOnly: true,
                required: true,
                withQuotes: false,
              },
            ],
          },
          {
            title: "regex_replace",
            type: "nested_without_title",
            required: false,
            options: [
              {
                title: "rule",
                type: "text",
                defaultValue: "regex_replace",
                readOnly: true,
                required: true,
                withQuotes: false,
              },
              {
                title: "match",
                type: "text",
                required: true,
                withQuotes: true,
              },
              {
                title: "replace",
                type: "text",
                required: true,
                withQuotes: false,
              },
            ],
          },
          {
            title: "truncate",
            type: "nested_without_title",
            required: false,
            options: [
              {
                title: "rule",
                type: "text",
                defaultValue: "truncate",
                readOnly: true,
                required: true,
                withQuotes: false,
              },
              {
                title: "max_length",
                type: "text",
                defaultValue: "128",
                required: false,
                withQuotes: false,
              },
            ],
          },
          {
            title: "upper_to_lower",
            type: "nested_without_title",
            required: false,
            options: [
              {
                title: "rule",
                type: "text",
                defaultValue: "upper_to_lower",
                readOnly: true,
                required: true,
                withQuotes: false,
              },
            ],
          },
          {
            title: "unique_number_suffix",
            type: "nested_without_title",
            required: false,
            options: [
              {
                title: "rule",
                type: "text",
                defaultValue: "unique_number_suffix",
                readOnly: true,
                required: true,
                withQuotes: false,
              },
              {
                title: "delimiter",
                type: "text",
                defaultValue: "_",
                required: false,
                withQuotes: true,
              },
              {
                title: "digits",
                type: "text",
                required: false,
                withQuotes: false,
              },
              {
                title: "max_length",
                type: "text",
                required: false,
                withQuotes: false,
              },
              {
                title: "offset",
                type: "text",
                defaultValue: "1",
                required: false,
                withQuotes: false,
              },
            ],
          },
        ],
      },
    ],
  },
  {
    title: "ruby_proc",
    type: "nested_without_title",
    required: false,
    options: [
      {
        title: "type",
        type: "text",
        defaultValue: "ruby_proc",
        readOnly: true,
        required: true,
        withQuotes: false,
      },
      {
        title: "requires",
        type: "array_of_strings",
        required: false,
        withQuotes: false,
      },
      {
        title: "variables",
        type: "nested",
        required: false,
        options: [
          {
            title: "multiply",
            type: "text",
            required: false,
            withQuotes: false,
          },
        ],
      },
      {
        title: "before",
        type: "array_of_objects",
        required: false,
        options: [
          {
            title: "proc",
            type: "textarea",
            required: true,
            withQuotes: false,
          },
        ],
      },
      {
        title: "after",
        type: "array_of_objects",
        required: false,
        options: [
          {
            title: "proc",
            type: "textarea",
            required: true,
            withQuotes: false,
          },
        ],
      },
      {
        title: "rows",
        type: "array_of_objects",
        required: false,
        options: [
          {
            title: "proc",
            type: "textarea",
            required: true,
            withQuotes: false,
          },
        ],
      },
      {
        title: "skip_rows",
        type: "array_of_objects",
        required: false,
        options: [
          {
            title: "proc",
            type: "textarea",
            required: true,
            withQuotes: false,
          },
        ],
      },
      {
        title: "columns",
        type: "array_of_objects",
        required: false,
        options: [
          {
            title: "name",
            type: "text",
            required: true,
            withQuotes: false,
          },
          {
            title: "proc",
            type: "textarea",
            required: false,
            withQuotes: false,
            hiddenWhen: "proc_file",
          },
          {
            title: "proc_file",
            type: "textarea",
            required: false,
            withQuotes: false,
            hiddenWhen: "proc",
          },
          {
            title: "skip_nil",
            type: "radio",
            options: ["true", "false"],
            required: false,
            withQuotes: false,
          },
          {
            title: "type",
            type: "text",
            required: false,
            withQuotes: false,
          },
        ],
      },
      {
        title: "pages",
        type: "array_of_objects",
        required: false,
        options: [
          {
            title: "proc",
            type: "textarea",
            required: true,
            withQuotes: false,
          },
        ],
      },
    ],
  },
  {
    title: "mysql_lookup",
    type: "nested_without_title",
    required: false,
    options: [
      {
        title: "type",
        type: "text",
        defaultValue: "mysql_lookup",
        readOnly: true,
        required: true,
        withQuotes: false,
      },
      {
        title: "host",
        type: "text",
        required: true,
        withQuotes: false,
      },
      {
        title: "port",
        type: "text",
        required: true,
        withQuotes: false,
      },
      {
        title: "database",
        type: "text",
        required: true,
        withQuotes: false,
      },
      {
        title: "tablename",
        type: "text",
        required: true,
        withQuotes: false,
      },
      {
        title: "username",
        type: "text",
        required: true,
        withQuotes: false,
      },
      {
        title: "password",
        type: "text",
        required: true,
        withQuotes: false,
      },
      {
        title: "mapping_from",
        type: "array_of_strings",
        required: false,
        withQuotes: false,
      },
      {
        title: "mapping_to",
        type: "array_of_strings",
        required: false,
        withQuotes: false,
      },

      {
        title: "new_columns",
        type: "array_of_objects",
        required: false,
        options: [
          {
            title: "name",
            type: "text",
            required: false,
            withQuotes: false,
          },
          {
            title: "type",
            type: "text",
            required: false,
            withQuotes: false,
          },
        ],
      },
    ],
  },
  {
    title: "oracle_lookup",
    type: "nested_without_title",
    required: false,
    options: [
      {
        title: "type",
        type: "text",
        defaultValue: "oracle_lookup",
        readOnly: true,
        required: true,
        withQuotes: false,
      },
      {
        title: "host",
        type: "text",
        required: true,
        withQuotes: false,
      },
      {
        title: "port",
        type: "text",
        required: true,
        withQuotes: false,
      },
      {
        title: "database",
        type: "text",
        required: true,
        withQuotes: false,
      },
      {
        title: "tablename",
        type: "text",
        required: true,
        withQuotes: false,
      },
      {
        title: "username",
        type: "text",
        required: true,
        withQuotes: false,
      },
      {
        title: "password",
        type: "text",
        required: true,
        withQuotes: false,
      },
      {
        title: "mapping_from",
        type: "array_of_strings",
        required: false,
        withQuotes: false,
      },
      {
        title: "mapping_to",
        type: "array_of_strings",
        required: false,
        withQuotes: false,
      },

      {
        title: "new_columns",
        type: "array_of_objects",
        required: false,
        options: [
          {
            title: "name",
            type: "text",
            required: false,
            withQuotes: false,
          },
          {
            title: "type",
            type: "text",
            required: false,
            withQuotes: false,
          },
        ],
      },
    ],
  },
  {
    title: "postgress_lookup",
    type: "nested_without_title",
    required: false,
    options: [
      {
        title: "type",
        type: "text",
        defaultValue: "postgress_lookup",
        readOnly: true,
        required: true,
        withQuotes: false,
      },
      {
        title: "host",
        type: "text",
        required: true,
        withQuotes: false,
      },
      {
        title: "port",
        type: "text",
        required: true,
        withQuotes: false,
      },
      {
        title: "database",
        type: "text",
        required: true,
        withQuotes: false,
      },
      {
        title: "tablename",
        type: "text",
        required: true,
        withQuotes: false,
      },
      {
        title: "username",
        type: "text",
        required: true,
        withQuotes: false,
      },
      {
        title: "password",
        type: "text",
        required: true,
        withQuotes: false,
      },
      {
        title: "mapping_from",
        type: "array_of_strings",
        required: false,
        withQuotes: false,
      },
      {
        title: "mapping_to",
        type: "array_of_strings",
        required: false,
        withQuotes: false,
      },
      {
        title: "new_columns",
        type: "array_of_objects",
        required: false,
        options: [
          {
            title: "name",
            type: "text",
            required: false,
            withQuotes: false,
          },
          {
            title: "type",
            type: "text",
            required: false,
            withQuotes: false,
          },
        ],
      },
    ],
  },
  {
    title: "mssql_lookup",
    type: "nested_without_title",
    required: false,
    options: [
      {
        title: "type",
        type: "text",
        defaultValue: "mssql_lookup",
        readOnly: true,
        required: true,
        withQuotes: false,
      },
      {
        title: "host",
        type: "text",
        required: true,
        withQuotes: false,
      },
      {
        title: "port",
        type: "text",
        required: false,
        withQuotes: false,
      },
      {
        title: "database",
        type: "text",
        required: true,
        withQuotes: false,
      },
      {
        title: "tablename",
        type: "text",
        required: true,
        withQuotes: false,
      },
      {
        title: "username",
        type: "text",
        required: true,
        withQuotes: false,
      },
      {
        title: "password",
        type: "text",
        required: true,
        withQuotes: false,
      },
      {
        title: "mapping_from",
        type: "array_of_strings",
        required: false,
        withQuotes: false,
      },
      {
        title: "mapping_to",
        type: "array_of_strings",
        required: false,
        withQuotes: false,
      },
      {
        title: "new_columns",
        type: "array_of_objects",
        required: false,
        options: [
          {
            title: "name",
            type: "text",
            required: false,
            withQuotes: false,
          },
          {
            title: "type",
            type: "text",
            required: false,
            withQuotes: false,
          },
        ],
      },
    ],
  },
  {
    title: "csv_lookup",
    type: "nested_without_title",
    required: false,
    options: [
      {
        title: "type",
        type: "text",
        defaultValue: "csv_lookup",
        readOnly: true,
        required: true,
        withQuotes: false,
      },
      {
        title: "mapping_from",
        type: "array_of_strings",
        required: false,
        withQuotes: false,
      },
      {
        title: "mapping_to",
        type: "array_of_strings",
        required: false,
        withQuotes: false,
      },
      {
        title: "new_columns",
        type: "array_of_objects",
        required: false,
        options: [
          {
            title: "name",
            type: "text",
            required: false,
            withQuotes: false,
          },
          {
            title: "type",
            type: "text",
            required: false,
            withQuotes: false,
          },
        ],
      },
    ],
  },
];
// schema end for filters plugin